---
# control
control:
  data_name: MNIST
  model_name: linear
  data_mode:
    num_splits: 2
    split_mode: horiz
    stat_mode: iid
  comm_mode:
    agg_mode: sync
    active_ratio: 1.0
    num_steps: 5
  test_mode: server
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cpu
resume_mode: 0
profile: False