---
# control
control:
  data_name: MNIST
  model_name: linear
  batch_size: 250
  step_period: 1
  num_steps: 400
  eval_period: 200
  optimizer_name: SGD
  lr: 0.1
  momentum: 0.9
  scheduler_name: CosineAnnealingLR
  data_mode:
    num_splits: 2
    split_mode: horiz
    stat_mode: iid
  dist_mode:
    agg_mode: sync
    active_ratio: 1.0
    num_steps: 100
    eval_mode: server
    optimizer_name: SGD
    lr: 0.03
    momentum: 0.9
    scheduler_name: None
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cpu
resume_mode: 0
profile: False