---
# control
control:
  data_name: MNIST
  model_name: linear
  batch_size: 250
  step_period: 1
  num_steps: 400
  eval_period: 200
  optimizer:
    optimizer_name: SGD
    lr: 1
    momentum: 0
    scheduler_name: None
  data_mode:
    num_splits: 2
    split_mode: horiz
    stat_mode: iid
  dist_mode:
    agg_mode: sync
    active_ratio: 1.0
    num_steps: 200
    eval_mode: server
    optimizer:
      optimizer_name: SGD
      lr: 0.01
      momentum: 0.9
      scheduler_name: CosineAnnealingLR
# experiment
pin_memory: True
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cpu
resume_mode: 0
profile: False